name: Trigger auto deployment for container-app-wdgfg5kdl5pzs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-wdgfg5kdl5pzs-AutoDeployTrigger-d61ce22d-49af-48f9-8859-3de2a6997017.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPWDGFG5KDL5PZS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPWDGFG5KDL5PZS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPWDGFG5KDL5PZS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPWDGFG5KDL5PZS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPWDGFG5KDL5PZS_REGISTRY_PASSWORD }}
          containerAppName: container-app-wdgfg5kdl5pzs
          resourceGroup: flaskbasica839bdbc
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


